export const CH = {
  relationshipGet: 'relationship:get',
  relationshipReset: 'relationship:reset',
  bootstrap: 'app:bootstrap',

  characterList: 'character:list',
  characterSave: 'character:save',
  characterDelete: 'character:delete',
  characterActivate: 'character:activate',
  personaList: 'persona:list',
  personaSave: 'persona:save',
  personaReset: 'persona:reset',
  personaDelete: 'persona:delete',
  personaImport: 'persona:import',
  personaPickFile: 'persona:pickFile',
  personaOpenDir: 'persona:openDir',
  personaPacks: 'persona:packs',

  conversationList: 'conversation:list',
  conversationCreate: 'conversation:create',
  conversationDelete: 'conversation:delete',
  messageList: 'message:list',
  messageAppend: 'message:append',

  chatSend: 'chat:send',
  chatAbort: 'chat:abort',
  chatStream: 'chat:stream',

  memoryList: 'memory:list',
  memoryAdd: 'memory:add',
  memoryDelete: 'memory:delete',
  memorySearch: 'memory:search',

  toolList: 'tool:list',
  toolRun: 'tool:run',
  toolApprove: 'tool:approve',

  settingsGet: 'settings:get',
  settingsSave: 'settings:save',
  settingsReset: 'settings:reset',

  voicePresets: 'voice:presets',
  voiceAssets: 'voice:assets',
  voiceResolve: 'voice:resolve',
  voiceImport: 'voice:import',
  voiceDelete: 'voice:delete',
  voicePickFile: 'voice:pickFile',

  inworldVoices: 'inworld:voices',
  inworldTest: 'inworld:test',
  inworldSynthesize: 'inworld:synthesize',
  inworldClone: 'inworld:clone',
  ttsProviders: 'tts:providers',
  ttsModels: 'tts:models',
  ttsSwitchProvider: 'tts:switchProvider',
  ttsLocalModels: 'tts:localModels',
  ttsLocalPickModel: 'tts:localPickModel',
  ttsLocalSetModel: 'tts:localSetModel',
  ttsLocalSynthesize: 'tts:localSynthesize',
  ttsLocalProbe: 'tts:localProbe',

  stickerList: 'sticker:list',
  stickerStats: 'sticker:stats',
  stickerPick: 'sticker:pick',
  stickerAdd: 'sticker:add',
  stickerPickFile: 'sticker:pickFile',
  stickerRemove: 'sticker:remove',
  stickerSearch: 'sticker:search',
  stickerScrape: 'sticker:scrape',
  stickerDownload: 'sticker:download',
  stickerOpenDir: 'sticker:openDir',
  stickerSend: 'sticker:send',

  ttsEnvStatus: 'ttsEnv:status',
  ttsEnvSetup: 'ttsEnv:setup',
  ttsEnvRemove: 'ttsEnv:remove',
  ttsEnvReport: 'ttsEnv:report',
  ttsEnvProgress: 'ttsEnv:progress',

  bgList: 'background:list',
  bgImport: 'background:import',
  bgPickFile: 'background:pickFile',
  bgDelete: 'background:delete',
  bgExternal: 'background:external',
  bgPatch: 'background:patch',
  bgReset: 'background:reset',

  themePresets: 'theme:presets',
  themeState: 'theme:state',
  themeSetActive: 'theme:setActive',
  themePatchCustom: 'theme:patchCustom',
  themeSetCustom: 'theme:setCustom',
  themeSaveCustom: 'theme:saveCustom',
  themeDeleteSaved: 'theme:deleteSaved',
  themeForkPreset: 'theme:forkPreset',
  themeResetCustom: 'theme:resetCustom',

  modelList: 'model:list',
  modelSelectable: 'model:selectable',
  modelSetActive: 'model:setActive',
  modelProbe: 'model:probe',
  modelAdd: 'model:add',
  modelRemove: 'model:remove',
  modelUpdate: 'model:update',
  modelMarkConnected: 'model:markConnected',
  modelState: 'model:state',
  modelDisconnect: 'model:disconnect',
  modelDisconnectAll: 'model:disconnectAll',

  attList: 'attachment:list',
  attPick: 'attachment:pick',
  attImport: 'attachment:import',
  attExternal: 'attachment:external',
  attDelete: 'attachment:delete',
  attOpen: 'attachment:open',

  agentTools: 'agent:tools',
  featureList: 'feature:list',
  featureToggle: 'feature:toggle',
  workspaceSecurity: 'workspace:security',
  workspaceTrust: 'workspace:trust',
  commandRuleSave: 'workspace:ruleSave',
  commandRuleRemove: 'workspace:ruleRemove',
  approvalsClear: 'workspace:approvalsClear',
  documentOpen: 'document:open',
  documentPick: 'document:pick',
  fileRoots: 'file:roots',
  agentRun: 'agent:run',
  agentJobs: 'agent:jobs',
  agentJobOutput: 'agent:jobOutput',
  agentJobKill: 'agent:jobKill',
  agentTodos: 'agent:todos',
  agentDeliverables: 'agent:deliverables',
  agentWorkspace: 'agent:workspace',
  agentSetWorkspace: 'agent:setWorkspace',
  agentPickWorkspace: 'agent:pickWorkspace',
  agentSkills: 'agent:skills',
  agentSkillLoad: 'agent:skillLoad',
  machinePermissionGet: 'agent:machinePermissionGet',
  machinePermissionSet: 'agent:machinePermissionSet',

  pluginList: 'plugin:list',
  pluginDir: 'plugin:dir',
  pluginImport: 'plugin:import',
  pluginRemove: 'plugin:remove',
  pluginToggle: 'plugin:toggle',
  pluginInvoke: 'plugin:invoke',
  pluginReveal: 'plugin:reveal',

  windowCloseAction: 'window:closeAction',
  windowGetClosePref: 'window:getClosePref',
  windowSetClosePref: 'window:setClosePref',
  windowShowCloseDialog: 'window:showCloseDialog',
  trayMenu: 'tray:menu',
  trayAction: 'tray:action',

  hardwareStatus: 'system:hardware',
  launchApp: 'system:launchApp',
  installedApps: 'system:installedApps',
  appClose: 'system:appClose',
  appRunningList: 'system:appRunningList',
  openExternal: 'system:openExternal',
  pickImage: 'system:pickImage',
  pickMedia: 'system:pickMedia',
  pickAudio: 'system:pickAudio',
  exportData: 'system:exportData',
  importData: 'system:importData',

  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',

  stickerProactive: 'sticker:proactive'
} as const
